name: batocera_remote
description: Télécommande Android pour Batocera Linux
version: 1.1.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartssh2: ^2.13.0
  shared_preferences: ^2.2.0
  provider: ^6.1.0
  path_provider: ^2.1.0
  open_filex: ^4.3.2
  file_picker: ^8.0.0
  share_plus: ^10.0.0
  flutter_pdfview: ^1.3.2
  url_launcher: ^6.2.0
  crypto: ^3.0.3
  video_player: ^2.8.0
  wakelock_plus: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#0D0F14"
  adaptive_icon_foreground: "assets/icon.png"
